import HomePageContent from "@/app/HomePageContent";
import { auth } from "@/auth";
import HeaderHome from "@/components/layout/HeaderHome";
import {
	createPageMetadata,
	generateFAQSchema,
	generateOrganizationSchema,
	generateWebApplicationSchema,
	getMetadataLocale,
	siteConfig,
} from "@/lib/seo";
import Script from "next/script";

const pageContent = {
	fr: {
		title: "Gestionnaire de Mots de Passe Sécurisé & Gratuit",
		description:
			"SkromaPASS protège vos mots de passe avec un chiffrement AES-256 de niveau militaire. Générateur intégré, 2FA, organisation par dossiers. 100% gratuit et open-source.",
		keywords: [
			"gestionnaire mots de passe en ligne gratuit",
			"password manager français",
			"coffre fort numérique gratuit",
			"stocker mots de passe sécurisé",
			"application gestion mot de passe",
			"meilleur gestionnaire mdp",
			"sécuriser ses mots de passe",
		],
	},
	en: {
		title: "Free & Secure Password Manager",
		description:
			"SkromaPASS protects your passwords with military-grade AES-256 encryption. Built-in generator, 2FA, folder organization. 100% free and open-source.",
		keywords: [
			"free online password manager",
			"secure password manager",
			"free digital vault",
			"secure password storage",
			"password management app",
			"best password manager",
			"secure your passwords",
		],
	},
};

const faqData = {
	fr: [
		{
			question: "SkromaPASS est-il vraiment gratuit ?",
			answer: "Oui, SkromaPASS est 100 % gratuit et open-source. Aucune carte bancaire ni abonnement n'est requis.",
		},
		{
			question: "Comment mes mots de passe sont-ils protégés ?",
			answer: "Vos mots de passe sont chiffrés avec l'algorithme AES-256 avant d'être stockés. Même nos serveurs ne peuvent pas lire vos données.",
		},
		{
			question: "SkromaPASS dispose-t-il d'une extension de navigateur ?",
			answer: "Oui, SkromaPASS propose une extension pour Chrome et Firefox qui remplit automatiquement vos identifiants sur les sites web.",
		},
		{
			question:
				"Qu'est-ce que l'authentification à deux facteurs (2FA) ?",
			answer: "La 2FA ajoute une couche de sécurité supplémentaire : en plus de votre mot de passe, un code unique généré par une application d'authentification est requis pour vous connecter.",
		},
		{
			question:
				"Puis-je accéder à mes mots de passe depuis plusieurs appareils ?",
			answer: "Oui, SkromaPASS est accessible depuis n'importe quel navigateur web. Vos données sont synchronisées en temps réel.",
		},
	],
	en: [
		{
			question: "Is SkromaPASS really free?",
			answer: "Yes, SkromaPASS is 100% free and open-source. No credit card or subscription is required.",
		},
		{
			question: "How are my passwords protected?",
			answer: "Your passwords are encrypted with AES-256 algorithm before being stored. Even our servers cannot read your data.",
		},
		{
			question: "Does SkromaPASS have a browser extension?",
			answer: "Yes, SkromaPASS offers an extension for Chrome and Firefox that automatically fills your credentials on websites.",
		},
		{
			question: "What is two-factor authentication (2FA)?",
			answer: "2FA adds an extra security layer: in addition to your password, a unique code generated by an authenticator app is required to log in.",
		},
		{
			question: "Can I access my passwords from multiple devices?",
			answer: "Yes, SkromaPASS is accessible from any web browser. Your data is synchronized in real time.",
		},
	],
};

export async function generateMetadata() {
	const locale = await getMetadataLocale();
	const { title, description, keywords } = pageContent[locale];
	return createPageMetadata(
		{ title, description, keywords, canonical: siteConfig.url },
		locale,
	);
}

export default async function HomePage() {
	const session = await auth();
	const isAuthenticated = !!session;
	const locale = await getMetadataLocale();

	const webAppSchema = generateWebApplicationSchema();
	const orgSchema = generateOrganizationSchema();
	const faqSchema = generateFAQSchema(faqData[locale] ?? faqData["fr"]);
	return (
		<>
			<Script
				id="schema-webapp"
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: JSON.stringify(webAppSchema),
				}}
			/>
			<Script
				id="schema-org"
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: JSON.stringify(orgSchema),
				}}
			/>
			<Script
				id="schema-faq"
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: JSON.stringify(faqSchema),
				}}
			/>
			<HeaderHome />
			<HomePageContent isAuthenticated={isAuthenticated} />
		</>
	);
}
